### ISSUE TITLE
OSError: Can't load the model for 'Rostlab/prot_t5_xl_half_uniref50-enc'

### ISSUE THREAD

**Issue by msarrias** [kWeissenow/EMBER3D#1]
Hi,

I'm trying to use EMBER3D to compute the structure prediction of a sequence in FASTA format. 

After running:

`python3 predict.py -i /home/x_maher/Homo_sapiens_akap5.fa -o /home/x_maher`

I get the following error:

```
Traceback (most recent call last):
  File "predict.py", line 31, in <module>
    Ember3D = Ember3D(args.model_checkpoint, args.t5_dir, args.device)
  File "/opt/EMBER3D/Ember3D.py", line 116, in __init__
    self.embedder = T5Embedder(t5_dir, device)
  File "/opt/EMBER3D/T5Embedder.py", line 12, in __init__
    self.model = T5EncoderModel.from_pretrained(transformer_link, cache_dir=t5_dir, output_attentions=True, torch_dtype=torch.float16)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1922, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 526, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for 'Rostlab/prot_t5_xl_half_uniref50-enc'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Rostlab/prot_t5_xl_half_uniref50-enc' is the correct path to a directory containing a config.json file
```

## Environment:
I'm currently working on a GPU node using a singularity container.
- Python 3.8.3
- CUDA Version: 11.7

**Comment by JinyuanSun** [comment]
I got the same issue.

**Comment by JinyuanSun** [comment]
A similar issue in the [previous](https://github.com/kWeissenow/EMBER2/issues/1) version.

**Comment by kWeissenow** [comment]
Thanks for reporting this issue!
On first use, EMBER3D will download ProtT5 model checkpoints. By default, the script will try to store those checkpoints in the directory 'ProtT5-XL-U50' within your current working directory.
Were model files downloaded at all or did you get some kind of error message? Could you please check whether you have write access in your working directory and if the directory 'ProtT5-XL-U50' was created at all?
You can also use the parameter --t5_model to point to a different location.

**Comment by JinyuanSun** [comment]
![image](https://user-images.githubusercontent.com/33344948/202443628-285bac2f-2ec3-4dfa-8c67-5631cdb4ccbf.png)
I got this error message and fixed by clone the `https://huggingface.co/Rostlab/prot_t5_xl_half_uniref50-enc` repo into `/path/to/EMBER3D/Rostlab/`.  
In some cluster, computation nodes have no access to the network.
