### ISSUE TITLE
render_mutation_movie.py command

### ISSUE THREAD

**Issue by JustineCharon** [kWeissenow/EMBER3D#2]
Hi,

Thanks for this amazing tool !!!
I've just ran successfully the SAV step but I can't make the PPM step working using the render_mutation_movie.py. I get the following error file :

```
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/EMBER3D/EMBER3D-45993b9/render_mutation_movie.py", line 144, in <module>
    main()
  File "/usr/local/bioinfo/src/EMBER3D/EMBER3D-45993b9/render_mutation_movie.py", line 110, in main
    write_png(id, pdb_file, png_file, width=movie_right_panel_x, height=movie_height)
  File "/usr/local/bioinfo/src/EMBER3D/EMBER3D-45993b9/render_mutation_movie.py", line 51, in write_png
    font = ImageFont.truetype("font.ttf", 16)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/EMBER3D-45993b9_env/lib/python3.8/site-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/EMBER3D-45993b9_env/lib/python3.8/site-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/envs/EMBER3D-45993b9_env/lib/python3.8/site-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

Thanks in advance for your help, can't wait to watch my new PPM ;)

Justine

**Comment by JustineCharon** [comment]
Issue fixed :)
